apiVersion: v2
name: telegraf
version: 1.8.7
appVersion: 1.20.2
deprecated: false
description: Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics.
keywords:
  - telegraf
  - collector
  - timeseries
  - influxdata
  - influxdb
  - agent
home: https://www.influxdata.com/time-series-platform/telegraf/
sources:
  - https://github.com/influxdata/helm-charts/tree/master/charts/telegraf
  - https://github.com/influxdata/helm-charts/
maintainers:
  - name: rawkode
    email: rawkode@influxdata.com
  - name: gitirabassi
    email: giacomo@influxdata.com
icon: https://avatars0.githubusercontent.com/u/5713248?s=200&v=4
