apiVersion: v1
name: telegraf
version: 1.7.0
appVersion: 1.13
deprecated: false
description: Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics.
keywords:
- telegraf
- collector
- timeseries
- influxdata
home: https://www.influxdata.com/time-series-platform/telegraf/
maintainers:
- name: David McKay
  email: rawkode@influxdata.com
- name: Giacomo Tirabassi
  email: giacomo@influxdata.com
- name: naseemkullah
  email: naseemkullah@gmail.com
engine: gotpl
