apiVersion: v1
version: 0.1.12
appVersion: 1.8.5
engine: gotpl

name: influxdb-enterprise
type: application
description: Run InfluxDB Enterprise on Kubernetes
keywords:
  - influxdb
  - database
  - timeseries
  - influxdata
home: https://www.influxdata.com/time-series-platform/influxdb/
sources:
  - https://github.com/influxdata/influxdb
maintainers:
  - name: rawkode
    email: david@rawkode.com
  - name: chobbs
    email: chobbs@influxdata.com
