apiVersion: v1
name: kapacitor
version: 1.4.3
appVersion: 1.6.3
description: InfluxDB's native data processing engine. It can process both stream
  and batch data from InfluxDB.
keywords:
- kapacitor
- stream
- etl
- timeseries
- influxdb
- influxdata
home: https://www.influxdata.com/time-series-platform/kapacitor/
sources:
- https://github.com/influxdata/kapacitor
maintainers:
- name: rawkode
  email: rawkode@influxdata.com
- name: gitirabassi
  email: giacomo@influxdata.com
- name: aisuko
  email: urakiny@gmail.com
engine: gotpl
