{{- if .Values.compactor.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-compactor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: compactor
spec:
  serviceName: {{ include "influxdb3-enterprise.fullname" . }}-compactor
  replicas: 1
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: compactor
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-object-storage.yaml") . | sha256sum }}
        {{- with .Values.compactor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "influxdb3-enterprise.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: compactor
        {{- with .Values.compactor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "influxdb3-enterprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.compactor.podSecurityContext | nindent 8 }}
      containers:
        - name: influxdb3
          image: {{ include "influxdb3-enterprise.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              exec influxdb3 \
                --num-io-threads={{ .Values.compactor.threads.io }} \
                serve \
                --node-id=$(hostname) \
                --cluster-id={{ .Values.cluster.id }} \
                --mode={{ .Values.compactor.mode }} \
                --datafusion-num-threads={{ .Values.compactor.threads.datafusion }} \
                --compaction-gen2-duration={{ .Values.compactor.compaction.gen2Duration }} \
                --compaction-multipliers={{ .Values.compactor.compaction.multipliers }} \
                --compaction-max-num-files-per-plan={{ .Values.compactor.compaction.maxNumFilesPerPlan }} \
                --compaction-cleanup-wait={{ .Values.compactor.compaction.cleanupWait }} \
                --compaction-check-interval={{ .Values.compactor.compaction.checkInterval }} \
                --gen1-duration={{ .Values.compactor.compaction.gen1Duration }} \
                --object-store={{ .Values.objectStorage.type }} \
              {{- if eq .Values.objectStorage.type "s3" }}
                --bucket={{ .Values.objectStorage.bucket }} \
                --aws-default-region={{ .Values.objectStorage.s3.region }} \
              {{- if .Values.objectStorage.s3.endpoint }}
                --aws-endpoint={{ .Values.objectStorage.s3.endpoint }} \
              {{- end }}
                --aws-allow-http={{ .Values.objectStorage.s3.allowHttp }} \
              {{- else if eq .Values.objectStorage.type "azure" }}
                --bucket={{ .Values.objectStorage.bucket }} \
              {{- else if eq .Values.objectStorage.type "google" }}
                --bucket={{ .Values.objectStorage.bucket }} \
              {{- else if eq .Values.objectStorage.type "file" }}
                --data-dir={{ .Values.objectStorage.file.dataDir }} \
              {{- end }}
                --http-bind={{ .Values.http.bind }} \
                --catalog-sync-interval={{ .Values.cluster.catalogSyncInterval }}
          env:
            - name: INFLUXDB3_ENTERPRISE_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "influxdb3-enterprise.fullname" . }}-config
                  key: cluster-id
        {{- if eq .Values.objectStorage.type "s3" }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "influxdb3-enterprise.objectStorageSecretName" . }}
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "influxdb3-enterprise.objectStorageSecretName" . }}
                  key: secret-access-key
        {{- end }}
        {{- if .Values.license.email }}
            - name: INFLUXDB3_ENTERPRISE_LICENSE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "influxdb3-enterprise.licenseSecretName" . }}
                  key: license-email
        {{- end }}
            - name: INFLUXDB3_ENTERPRISE_LICENSE_TYPE
              value: {{ .Values.license.type | quote }}
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.compactor.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.compactor.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.compactor.resources | nindent 12 }}
          {{- if eq .Values.objectStorage.type "file" }}
          volumeMounts:
            - name: object-storage
              mountPath: {{ .Values.objectStorage.file.dataDir }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- with .Values.compactor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.compactor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.compactor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.objectStorage.type "file" }}
      volumes:
        - name: object-storage
          persistentVolumeClaim:
            claimName: {{ include "influxdb3-enterprise.fullname" . }}-object-storage
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
