{{- if and .Values.ingester.podDisruptionBudget.enabled .Values.ingester.enabled (gt (int .Values.ingester.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-ingester
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
spec:
  minAvailable: {{ .Values.ingester.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingester
{{- end }}
