{{- if .Values.ingress.query.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-query
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress-query
  {{- with .Values.ingress.query.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.query.className }}
  ingressClassName: {{ .Values.ingress.query.className }}
  {{- end }}
  {{- if .Values.ingress.query.tls }}
  tls:
    {{- range .Values.ingress.query.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api/v3/query
            pathType: Prefix
            backend:
              service:
                name: {{ include "influxdb3-enterprise.fullname" . }}-querier
                port:
                  number: {{ .Values.querier.service.port }}
          - path: /query
            pathType: Prefix
            backend:
              service:
                name: {{ include "influxdb3-enterprise.fullname" . }}-querier
                port:
                  number: {{ .Values.querier.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "influxdb3-enterprise.fullname" . }}-querier
                port:
                  number: {{ .Values.querier.service.port }}
{{- end }}
