{{- if and .Values.ingester.podDisruptionBudget.enabled .Values.ingester.enabled (gt (int .Values.ingester.replicas) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-ingester
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
spec:
  maxUnavailable: {{ .Values.ingester.podDisruptionBudget.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingester
{{- end }}
{{- if and .Values.querier.podDisruptionBudget.enabled .Values.querier.enabled (gt (int .Values.querier.replicas) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-querier
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier
spec:
  maxUnavailable: {{ .Values.querier.podDisruptionBudget.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: querier
{{- end }}
{{- if and .Values.processingEngine.podDisruptionBudget.enabled .Values.processingEngine.enabled (gt (int .Values.processingEngine.replicas) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-processor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
spec:
  maxUnavailable: {{ .Values.processingEngine.podDisruptionBudget.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: processor
{{- end }}
{{- if and .Values.compactor.podDisruptionBudget.enabled .Values.compactor.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-compactor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: compactor
spec:
  maxUnavailable: {{ .Values.compactor.podDisruptionBudget.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: compactor
{{- end }}
