{{- if .Values.processingEngine.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-processor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
spec:
  serviceName: {{ include "influxdb3-enterprise.fullname" . }}-processor
  replicas: {{ .Values.processingEngine.replicas }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: processor
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-object-storage.yaml") . | sha256sum }}
        {{- with .Values.processingEngine.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "influxdb3-enterprise.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: processor
        {{- with .Values.processingEngine.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "influxdb3-enterprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.processingEngine.podSecurityContext | nindent 8 }}
      containers:
        - name: influxdb3
          securityContext:
          {{- toYaml .Values.processingEngine.securityContext | nindent 10 }}
          image: {{ include "influxdb3-enterprise.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              exec influxdb3 \
                --num-io-threads={{ .Values.processingEngine.threads.io }} \
                serve \
                --node-id=$(hostname) \
                --cluster-id={{ .Values.cluster.id }} \
                --mode={{ .Values.processingEngine.mode }} \
                --datafusion-num-threads={{ .Values.processingEngine.threads.datafusion }} \
                --plugin-dir={{ .Values.processingEngine.pluginDir }} \
              {{- if .Values.processingEngine.pluginRepo }}
                --plugin-repo={{ .Values.processingEngine.pluginRepo }} \
              {{- end }}
                --package-manager={{ .Values.processingEngine.packageManager }} \
                --object-store={{ .Values.objectStorage.type }} \
              {{- if eq .Values.objectStorage.type "s3" }}
                --bucket={{ .Values.objectStorage.bucket }} \
                --aws-default-region={{ .Values.objectStorage.s3.region }} \
              {{- if .Values.objectStorage.s3.endpoint }}
                --aws-endpoint={{ .Values.objectStorage.s3.endpoint }} \
              {{- end }}
                --aws-allow-http={{ .Values.objectStorage.s3.allowHttp }} \
              {{- else if eq .Values.objectStorage.type "azure" }}
                --bucket={{ .Values.objectStorage.bucket }} \
              {{- else if eq .Values.objectStorage.type "google" }}
                --bucket={{ .Values.objectStorage.bucket }} \
              {{- else if eq .Values.objectStorage.type "file" }}
                --data-dir={{ .Values.objectStorage.file.dataDir }} \
              {{- end }}
                --http-bind={{ .Values.http.bind }} \
                --catalog-sync-interval={{ .Values.cluster.catalogSyncInterval }}
          env:
            - name: INFLUXDB3_ENTERPRISE_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "influxdb3-enterprise.fullname" . }}-config
                  key: cluster-id
        {{- if eq .Values.objectStorage.type "s3" }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "influxdb3-enterprise.objectStorageSecretName" . }}
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "influxdb3-enterprise.objectStorageSecretName" . }}
                  key: secret-access-key
        {{- end }}
        {{- if .Values.license.email }}
            - name: INFLUXDB3_ENTERPRISE_LICENSE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "influxdb3-enterprise.licenseSecretName" . }}
                  key: license-email
        {{- end }}
            - name: INFLUXDB3_ENTERPRISE_LICENSE_TYPE
              value: {{ .Values.license.type | quote }}
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
          {{- toYaml .Values.processingEngine.livenessProbe | nindent 10 }}
          readinessProbe:
          {{- toYaml .Values.processingEngine.readinessProbe | nindent 10 }}
          resources:
          {{- toYaml .Values.processingEngine.resources | nindent 10 }}
          volumeMounts:
          {{- if .Values.processingEngine.persistence.enabled }}
            - name: plugins
              mountPath: {{ .Values.processingEngine.pluginDir }}
          {{- end }}
          {{- if eq .Values.objectStorage.type "file" }}
            - name: object-storage
              mountPath: {{ .Values.objectStorage.file.dataDir }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- with .Values.processingEngine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.processingEngine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.processingEngine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if eq .Values.objectStorage.type "file" }}
        - name: object-storage
          persistentVolumeClaim:
            claimName: {{ include "influxdb3-enterprise.fullname" . }}-object-storage
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- if .Values.processingEngine.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: plugins
      spec:
        accessModes:
          - {{ .Values.processingEngine.persistence.accessMode }}
      {{- if .Values.processingEngine.persistence.storageClass }}
        storageClassName: {{ .Values.processingEngine.persistence.storageClass | quote }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.processingEngine.persistence.size }}
  {{- end }}
{{- end }}
