{{- if .Values.processingEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-processor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
  {{- with .Values.processingEngine.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.processingEngine.service.type }}
  ports:
    - port: {{ .Values.processingEngine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "influxdb3-enterprise.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: processor
{{- end }}
