{{- if and .Values.querier.podDisruptionBudget.enabled .Values.querier.enabled (gt (int .Values.querier.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-querier
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier
spec:
  {{- if .Values.querier.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.querier.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.querier.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.querier.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: querier
{{- end }}
