{{- if .Values.querier.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-querier
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier
spec:
  serviceName: {{ include "influxdb3-enterprise.fullname" . }}-querier
  replicas: {{ .Values.querier.replicas }}
  {{- if .Values.querier.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.querier.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "influxdb3-enterprise.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: querier
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-object-storage.yaml") . | sha256sum }}
        checksum/license: {{ include "influxdb3-enterprise.licenseChecksum" . }}
        {{- with .Values.querier.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "influxdb3-enterprise.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: querier
        {{- with .Values.querier.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "influxdb3-enterprise.serviceAccountName" . }}
      {{- if .Values.querier.priorityClassName }}
      priorityClassName: {{ .Values.querier.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.querier.podSecurityContext | nindent 8 }}
      containers:
        - name: influxdb3
          image: {{ include "influxdb3-enterprise.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              exec influxdb3 --num-io-threads={{ .Values.querier.numIOThreads }} serve \
                --mode=query \
                --node-id=$(hostname) \
                --datafusion-num-threads={{ .Values.querier.datafusion.numThreads }}
          envFrom:
            - configMapRef:
                name: {{ include "influxdb3-enterprise.fullname" . }}-config
          env:
            {{- include "influxdb3-enterprise.licenseEnv" . | nindent 12 }}
            {{- include "influxdb3-enterprise.objectStoreSecretEnv" . | nindent 12 }}
            {{- with .Values.querier.memory }}
            {{- if .execMemPoolBytes }}
            - name: INFLUXDB3_EXEC_MEM_POOL_BYTES
              value: {{ .execMemPoolBytes | quote }}
            {{- end }}
            {{- if .forceSnapshotMemThreshold }}
            - name: INFLUXDB3_FORCE_SNAPSHOT_MEM_THRESHOLD
              value: {{ .forceSnapshotMemThreshold | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.querier.datafusion }}
            {{- if .maxParquetFanout }}
            - name: INFLUXDB3_DATAFUSION_MAX_PARQUET_FANOUT
              value: {{ .maxParquetFanout | quote }}
            {{- end }}
            {{- if .config }}
            - name: INFLUXDB3_DATAFUSION_CONFIG
              value: {{ .config | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          {{- include "influxdb3-enterprise.probes" . | nindent 10 }}
          resources:
            {{- toYaml .Values.querier.resources | nindent 12 }}
          volumeMounts:
            {{ include "influxdb3-enterprise.sharedVolumeMounts" . | nindent 12 }}
      {{- with .Values.querier.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{ include "influxdb3-enterprise.sharedVolumes" . | nindent 8 }}
{{- end }}
