{{- if not .Values.license.existingSecret }}
{{- if or .Values.license.email .Values.license.file }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb3-enterprise.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "influxdb3-enterprise.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.license.email }}
  license-email: {{ .Values.license.email | b64enc | quote }}
  {{- end }}
  {{- if .Values.license.file }}
  license-file: {{ .Values.license.file | b64enc | quote }}
  {{- end }}
  license-type: {{ .Values.license.type | b64enc | quote }}
{{- end }}
{{- end }}
