apiVersion: v1
name: influxdb
version: 4.9.14
appVersion: 1.8.4
description: Scalable datastore for metrics, events, and real-time analytics.
keywords:
  - influxdb
  - database
  - timeseries
  - influxdata
home: https://www.influxdata.com/time-series-platform/influxdb/
sources:
  - https://github.com/influxdata/influxdb
maintainers:
  - name: rawkode
    email: rawkode@influxdata.com
  - name: gitirabassi
    email: giacomo@influxdata.com
  - name: aisuko
    email: urakiny@gmail.com
  - name: naseemkullah
    email: naseem@transit.app
engine: gotpl
