apiVersion: v1
name: telegraf-ds
version: 1.0.3
appVersion: 1.13
deprecated: false
description: Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics.
keywords:
- telegraf
- collector
- timeseries
- influxdata
home: https://www.influxdata.com/time-series-platform/telegraf/
maintainers:
- name: rawkode
  email: rawkode@influxdata.com
- name: gitirabassi
  email: giacomo@influxdata.com
- name: naseemkullah
  email: naseemkullah@gmail.com
- name: nsteinmetz
  email: contact@cerenit.fr
engine: gotpl
