apiVersion: v1
name: chronograf
version: 1.2.2
appVersion: 1.9.1
description: Open-source web application written in Go and React.js that provides
  the tools to visualize your monitoring data and easily create alerting and automation
  rules.
keywords:
- chronograf
- visualizaion
- timeseries
- influxdata
- influxdb
home: https://www.influxdata.com/time-series-platform/chronograf/
maintainers:
- name: rawkode
  email: rawkode@influxdata.com
- name: gitirabassi
  email: giacomo@influxdata.com
engine: gotpl
