apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "telegraf-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telegraf-operator.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "telegraf-operator.selectorLabels" . | nindent 6 }}
