apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb-enterprise.fullname" . }}-meta
  labels:
    influxdb.influxdata.com/component: meta
    influxdb.influxdata.com/role: follower
    {{- include "influxdb-enterprise.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8089
    protocol: TCP
    name: raft
  - port: 8091
    protocol: TCP
    name: http
  selector:
    influxdb.influxdata.com/component: meta
    influxdb.influxdata.com/role: follower
    {{- include "influxdb-enterprise.selectorLabels" . | nindent 4 }}
