apiVersion: v2
name: telegraf-operator
description: A Helm chart for Kubernetes to deploy telegraf-operator
keywords:
  - telegraf
  - telegraf-operator
  - sidecar
  - operator
  - injector
  - mutatingwebhook
  - influxdata
  - influxdb

maintainers:
- name: wojciechka
  email: wkocjan@influxdata.com
- name: rawkode

kubeVersion: ">= 1.13.0-r0"
home: https://github.com/influxdata/telegraf-operator
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.3.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: v1.3.5
