apiVersion: v2
appVersion: 2.0.6

name: influxdb2
description: A Helm chart for InfluxDB v2
home: https://www.influxdata.com/products/influxdb-overview/influxdb-2-0/
type: application
version: 2.0.1
maintainers:
  - name: rawkode
    email: rawkode@influxdata.com
  - name: gitirabassi
    email: giacomo@influxdata.com
icon: https://avatars0.githubusercontent.com/u/5713248?s=200&v=4
